### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/6b4fec0f21ce52aebc80204c2d5c4849.png"):

### ISSUE THREAD

**Issue by chrisdobler** [spark-solutions/spark-starter-kit#55]
I've been having this issue with Rails not being able to reference image assets. The file is clearly there in the webpack folder, but Rails is unable to route it. Please let me know if you know what I'm doing wrong. Thanks.

The image does load in the webpack, but before that the above error is yielded. Perhaps I am referencing images improperly? This is how I'm referencing images:

`<img src={require("../../img/section1.png")} />`

**Comment by chrisdobler** [comment]
In a simple example I replaced the binary file client/js/components/Header/logo.png and suddenly I now get this error.

**Comment by krzysiek1507** [comment]
Hi @chrisdobler What is the size of the picture?

**Comment by chrisdobler** [comment]
they range from 100kb and up. Whats the limit on the embedded images? I couldn't find that in the config.

**Comment by chrisdobler** [comment]
I realized I could suppress the error message by turning off the prerender option in the rails view. I don't understand the implications of doing that though.

**Comment by ridem** [comment]
The "limit" is set in [webpack.client.base.config.js](https://github.com/spark-solutions/spark-starter-kit/blob/master/client/webpack.client.base.config.js#L70)
10000 = 10Kb. Under this limit, it loads as "a url", going your HTML payload. Above, it's using a regular file.

It's not supposed to behave like this though. You probably don't want to remove server rendering either, because it's a key feature of this project.

I think I remember having a very similar issue when deploying such images, the image was passed into /assets/ but the routing in the build was wrong.
I'll feed this issue if I come across this issue again or if I can reproduce it

**Comment by ridem** [comment]
I can indeed reproduce the issue. If you try accessing `/public/6b4fec0f21ce52aebc80204c2d5c4849.png` instead of `/6b4fec0f21ce52aebc80204c2d5c4849.png`, you will see it's going through the asset pipeline.

I think it's a webpack issue, but I don't have time to look at it right now.

**Comment by chrisdobler** [comment]
thank you for the response as well as the explanations. I guess I'll remove server rendering temporarily until its patched.

**Comment by chrisdobler** [comment]
I tried uploading to Heroku and am having the same issue in production.
